new_website/my_app/urls.py
from django.urls import path
from django.contrib import admin
from . import views


urlpatterns=[

    path('',views.index,name='index'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    
    path('logout',views.logout,name='logout'),
    path('create',views.createrecord,name='create'),
    path('update/<int:pk>',views.updaterecord,name='update'),
    path('delete/<int:pk>',views.deleterecord,name='delete'),
    path('dashboard',views.dashboard.as_view(),name='dashboard'),
   
]

new_website/new_website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('my_app.urls'))

]

new_website/my_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Record(models.Model):
    first_name=models.CharField(max_length=200,blank=True)
    last_name=models.CharField(max_length=140)
    email=models.EmailField()
    created_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
      return  self.first_name + " "+self.last_name
class ProfileInfo(models.Model):
   user=models.OneToOneField(User,on_delete=models.CASCADE)

   portfolio=models.URLField(blank=True)

   def __str__(self):
      return self.user.username
          

new_website/my_app/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.forms.widgets import PasswordInput,TextInput
from .models import Record


class CreateUserForm(UserCreationForm):

    class Meta:
        model=User
        fields=['username','password1','password2',]
        #fields='__all__'

class LoginForm(AuthenticationForm):
    username=forms.CharField(widget=TextInput())
    password=forms.CharField(widget=PasswordInput())

class CreateRecordForm(forms.ModelForm):  

    class Meta:
        model=Record
        fields=('first_name','last_name','email')
    
               

new_website/my_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import LoginForm,CreateUserForm,CreateRecordForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import auth
from django.contrib.auth.decorators import login_required
from .models import Record
from django.http import HttpResponse
from django.contrib import messages
from django.views.generic import ListView,UpdateView
from . import models

# Create your views here.

def index(request):
    return render(request,'index.html',)


def register(request):
    form=CreateUserForm()
    if request.method=='POST':
        form=CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Account created successfully!')
        else:
            form=CreateUserForm()
                
        return redirect('login')            
    context={'form':form}       
    return render(request,'register.html',context=context) 


def login(request):
    form=LoginForm()
    if request.method =='POST':
        form=LoginForm(request,data=request.POST)
        if form.is_valid():
            username=request.POST.get('username')
            password=request.POST.get('password')
            user=authenticate(request,username=username,password=password)
            if user is not None:
                auth.login(request,user)
                messages.success(request,'Login successfully')
            return redirect('dashboard')    
    context={'form':form}
    return render(request,'login.html',context=context)    


class dashboard(ListView):
    #context_object_name='anything'
    model=models.Record
    template_name='dashboard.html'
    # def dashboard(request):
#     my_record=Record.objects.all()
#     context={'record':my_record}
#     return render(request,'dashboard.html',context=context)
    


@login_required(login_url='login')
def createrecord(request):
    form=CreateRecordForm()
    if request.method=='POST':
        form=CreateRecordForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,'User Created successfully')
        return redirect('dashboard') 
      
    context={'form':form}
    return render(request,'create_record.html',context)

def updaterecord(request,pk):

    record=Record.objects.get(id=pk)
    form=CreateRecordForm(instance=record)
    if request.method=='POST':
        form=CreateRecordForm(request.POST,instance=record)
        if form.is_valid():
               form.save()
               messages.success(request,'Record update successfully')   
        return redirect('dashboard')  
    context={'form':form}  
    return render(request,'update.html',context) 



# class updaterecord(UpdateView):
#     fields=('First_name','Last_name')
#     model=models.Record


def deleterecord(request,pk):
    form=Record.objects.get(id=pk)   
    form.delete()
    return redirect('dashboard') 
      

  

def logout(request):
    auth.logout(request)

    return redirect('login')

class template(ListView):
    model=models.Record
    template_name='register.html'



           

new_website/my_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'mycss.css' %}">
    <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Document</title>
</head>
<body>

    {% include 'navbar.html' %}

    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}


    <p id="text-message" class="alert alert-success float-center text-center text-message" ><i class="fa fa-check" aria-hidden="true"></i>&nbsp; {{message}}</p>

    {% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}


    <p id="text-message-ERROR" class="alert alert-danger folat-center text-center text-message" ><i class="fa fa-check" aria-hidden="true"></i>&nbsp; {{message}}</p>

    {% endif %}


    {% endfor %}

    {% block content %}


    {% endblock %}

    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'myjs.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    
</body>
</html>

new_website/my_app/templates/create_record.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<body>
    <div class="conatainer p-3 shadow-md bg-light form-layout">

        <h3>Please Create Your Record</h3><br>
        

        <form method="POST" autocomplete="off">
            {% csrf_token %}


            {{form|crispy}}
            <button type="submit" class="btn btn-success">Create Account</button>
            

        </form>
    </div>
    <br>
</body>


{% endblock content %}

new_website/my_app/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

<h2 style="color:aqua;margin-top:20px">Welcome to Dashboard-page!!!!{{user}}</h1>

    <a href="{% url 'create' %}" class="btn btn-outline-primary">
        Create Record
    </a><br><br> 

    <table class="table table-light table-hover">
        <thead class="table-dark">
            <tr>
                <th scope="col">Id</th>      
                <th scope="col">First_name</th>
                <th scope="col">Last_name</th>
                <th scope="col"></th>
                <th scope="col"></th>

            </tr> 
        </thead>
        <tbody>
           
             
            {% for record in record_list  %}
            <tr>
                <td>{{record.id}}</td>
                <td>{{record.first_name}}</td>
                <td>{{record.last_name}}</td>
                <td><a href="{% url 'update' record.id %}"><input type="submit" class="btn btn-success" value="Update"></a></td>
                <td><a href="{% url 'delete' record.id %}"><input type="submit" class="btn btn-danger" value="Delete"></a></td>
            </tr> 

         {% endfor %}
                  
           
      
        </tbody>
    </table>

{% endblock %}

new_website/my_app/templates/index.html
{% extends 'base.html' %}



{% block content %}

<body>
   
    <br><br>
    <div class="text-center">
        <h2>Project-V.....My own project</h2><br>
        <h3>Please login into this site</h3>
        <hr>
        <br>

        <a class="btn btn-success" href="{% url 'register' %}">Create Your Account</a>
    </div>

    
    
</body>


{% endblock  %}

new_website/my_app/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<body>
    <div class="conatainer p-3 shadow-md bg-light form-layout">

        <h3>Please login with valid credentials</h3><br>
        <h5>Start your journey</h5><br>

        <form method="POST" autocomplete="off">
            {% csrf_token %}


            {{form|crispy}}
            <button type="submit" class="btn btn-success">Login Account</button>
            <div class="text-center ">

                <p>Don't have an Account?</p><a href="{% url 'register' %}">Register</a>
        
            </div>

        </form>
    </div>
    <br>

    
       

   
</body>

{% endblock %}

new_website/my_app/templates/navbar.html
<!DOCTYPE html>
<html>
<head>
<style>
ul.navbar_one {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: hsl(0, 0%, 7%);
  display: flex;
 
 
}

ul.navbar_one li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover {
  color: #11dd55;
}
li.logout {
 margin-left: 1000px;
}

</style>
</head>
<body>

<ul class="navbar_one">
  <li><a class="" href="#home">Project-V</a></li>
  <li><a href="{% url 'register' %}">Register</a></li>
  <li><a href="{% url 'login' %}"> Login</a></li>
  
  <li class="about"><a href="{% url 'dashboard' %}">Dashboard &nbsp; <i class="fa fa-tachometer" aria-hidden="true"></i></a></li>
  <li class="logout"><a href="{% url 'logout'  %}">Logout &nbsp; <i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
</ul>

</body>
</html>

new_website/my_app/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}


<body>
     <br>
    <div class="container bg-light shadow-md p-3 form-layout">

        <h3>Create your account Here</h3><br>
        <h5>start your journey Today</h5><hr><br>


        <form method="POST"  autocomplete="off">
            {% csrf_token %}


        <!-- {{form.as_p}} -->
            {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Create Account</button>


       </form>
       <br>


    </div>
    <br>

    <div class="text-center ">

        <p>Are you already a User?</p><a href="{% url 'login' %}">Login</a>

    </div>


</body>

{% endblock %}

new_website/my_app/templates/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<body>
    <div class="conatainer p-3 shadow-md bg-light form-layout">

        <h3>Please Update Your Record</h3><br>
        

        <form method="POST" autocomplete="off">
            {% csrf_token %}


            {{form|crispy}}
            <button type="submit" class="btn btn-success">Updated Details</button>
            

        </form>
    </div>
    <br>
</body>


{% endblock content %}